# Generated by Django 2.2 on 2019-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.ImageField(default='', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
