# Generated by Django 2.2 on 2019-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
