# Generated by Django 2.2 on 2019-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.TextField(),
        ),
    ]
