# Generated by Django 2.2 on 2019-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
