# Generated by Django 2.2 on 2019-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categories_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
