# Generated by Django 2.2 on 2019-07-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190718_1214'),
        ('blog', '0011_auto_20190705_1501'),
    ]

    operations = [
    ]
