# Generated by Django 2.2 on 2019-08-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
