# Generated by Django 2.2 on 2019-09-17 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20190916_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='blog_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
